version: "3"

services:
  latex:
    build:
      context: image
      dockerfile: Dockerfile
    container_name: latex
    stdin_open: true
    tty: true
    volumes:
      - <mount_path>:/latex
    ports:
      - "4321:22"
